"use client"
import './globals.css'
import NavBar from './components/NavBar'
import { useState } from 'react'
import { classNames } from '@/utils/utils'
import useWindowSize from '@/hooks/useWindowSize'





export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {

  const { width } = useWindowSize()

  const [menu, setMenu] = useState(false)

  const handleMenu = () => {
    setMenu(!menu)
    console.log(menu)
  }

  return (
    <html lang="en">
      <body className={classNames('scroll-smooth',
        menu ? 'overflow-hidden' : '')}>
        <div className={classNames('w-full flex items-center justify-center top-0 absolute  z-40 transition-all duration-500',
          menu ? 'h-full fixed bg-blue-500 py-10' : 'h-max bg-transparent')}>
          <button onClick={handleMenu}
            className={classNames('bg-blue-500 md:hidden  absolute top-4 right-4 z-50 p-4 rounded-xl',
              width > 600 ? 'hidden' : 'flex'
            )}>
            menu
          </button>
          <NavBar menu={menu} handleMenu={handleMenu} />
        </div>
        {children}
      </body>
    </html>
  )
}
